server:
  port: 8080
#  servlet:
#    context-path: /boot
  multipart:
    location: D:/upoadFile/



spring:
  #激活哪一个环境的配置文件
  profiles:
    active: dev
#  mvc:
#    #thymeleaf模版
#    static-path-pattern: /images/**
    view:
      prefix: /templates/
      suffix: .html


  thymeleaf:
    cache: false
    check-template: true
    check-template-location : true
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

# 静态文件请求匹配方式


  # 修改默认的静态寻址资源目录
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${server.multipart.location}


  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type : com.alibaba.druid.pool.DruidDataSource



mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.json.jdbcdemo.pojo
